### ISSUE TITLE
about channel attention

### ISSUE THREAD

**Issue by chensming** [Andrew0613/X-Restormer#2]
Hi, I wonder why channel attention is implemented in this way？
https://github.com/Andrew0613/X-Restormer/blob/c8c2b09005fda33eeb146f785d910d4573e27e29/xrestormer/archs/xrestormer_arch.py#L155-L186

In my impression, what you implement is the mechanism of self-attention. The channel attention mechanism may be implemented in the following ways.
```python
class ChannelAttention(nn.Module):
    def __init__(self, dim, reduction = 8):
        super(ChannelAttention, self).__init__()
        self.ca = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(dim, dim // reduction, 1, padding=0, bias=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(dim // reduction, dim, 1, padding=0, bias=True),
        )

    def forward(self, x):
        x = self.ca(x)  * x
        return x
```
Thank you in advance for your reply！

**Comment by Andrew0613** [comment]
You can regard our channel attention as implementing self-attention on channel dimensions. It is some kind of high-level version of the channel attention you mentioned. These two mechanisms both reweight channel information but in different ways.

**Comment by chensming** [comment]
> You can regard our channel attention as implementing self-attention on channel dimensions. It is some kind of high-level version of the channel attention you mentioned. These two mechanisms both reweight channel information but in different ways.

OK, Thanks.
